[package]
name = "rpdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
